### ISSUE TITLE
`RSpec/EmptyExampleGroup` allowed example group types

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop-rspec#1127]
I have a special `endpoint` example group, which I have defined as an example group in `RSpec/Language/ExampleGroups/Regular`. However, it is valid for this to have no body, because the `endpoint` method calls `it_behaves_like`, so there are implicit examples, even if it appears blank.

It'd be great if `RSpec/EmptyExampleGroup` could have a configuration to allow me to ignore certain example group "types" so that this can be ignored while other empty example groups can still register offenses.

eg:

```ruby
RSpec.describe API::FooController do
  endpoint :index, path: '/foo'
end

RSpec.describe API::BarController do
  endpoint :show, path: '/bar/:id' do
    it 'does something'
    # ...
  end
end
```

```
spec/test_spec.rb:1:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
RSpec.describe API::FooController do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pirj** [comment]
I would suggest adding `endpoint` to `Includes/Examples` instead, just like e.g. [`ActionPolicy` did](https://github.com/palkan/action_policy/pull/138/files#diff-7a633d5704411354d8906e8b463afd2c72bb4f1f12c7049b0e63e410047db58eR10). Will that work for you?

**Comment by dvandersluis** [comment]
@pirj oh cool! That does indeed avoid the offense from `RSpec/EmptyExampleGroup`.... but it adds one from `RSpec/SharedExamples` instead 🤦.

**Comment by pirj** [comment]
The original problem is kind of weird, though.
For the following code:
```ruby
  describe 'one'

  describe 'two' do
  end
```
only the second example group is marked as offensive. 🤔

**Comment by dvandersluis** [comment]
Sorry about that, issue from trying to simplify my code for sake of example. I updated the issue to show the error I was getting.

**Comment by dvandersluis** [comment]
@pirj I'm going to close this because you've solved my problem, so thanks! If you have any idea for how I could exclude these from `RSpec/SharedExamples`, please let me know, but that's a separate issue. In the meantime, I work a little shim for the cop in my own project to avoid the offense for `endpoint`.

**Comment by pirj** [comment]
There's only one thing that comes to mind given that `endpoint` is such a hybrid that semantics of an include and the syntax of an example group. I'm inclined to advise configuring it as an alias to a `Includes`, and dealing with SharedExamples separately.

Speaking of which:
```ruby
      #   # bad
      #   it_behaves_like :foo_bar_baz
      #   it_should_behave_like :foo_bar_baz
      #   shared_examples :foo_bar_baz
      #   shared_examples_for :foo_bar_baz
      #   include_examples :foo_bar_baz
```

Since for a shared group to be included, it should exist in the first place. That means that basically at least two offences will be raised, for the shared example group definition, and for the usage of such an example group.

In the case where the definition of an example group name is out of the responsibility of the consumer (e.g. `shared_examples_for :ouch_oh_i_define_it_as_a_symbol_deal_with_it do` defined in a third-party gem), the consuming code will be offensive even if it's out of their responsibility to fix that naming.

I suggest removing `#Includes.all` from the detection of `RSpec/SharedExamples`. WDYT @bquorning @Darhazer ?

On the other hand, I often see projects running `rubocop` only on the files changed in the pull request, and that change would make the issue with poorly-defined shared example names less visible.
To counter-argument myself, to fix such an offence would require fixing the file defining the shared example, and its potentially numerous usages, starting an avalanche of offence fixes, or a merge with red `rubocop`.

**Comment by pirj** [comment]
You are always welcome, @dvandersluis!
