### ISSUE TITLE
Cop idea: no subject/let/before after an example

### ISSUE THREAD

**Issue by Darhazer** [rubocop-hq/rubocop-rspec#376]
There will be good to have some cops that force the structure of an example group.
Having definition of let after the first example seems like a smell; and having the subject defined after an example is even worse. ScatteredLet only checks if the let are grouped together, but not if they are in the beginning of the example group.

**Comment by dgollahon** [comment]
I like this idea 👍

**Comment by Darhazer** [comment]
#394 already handles part of this.

**Comment by Darhazer** [comment]
#619 handles the part with the subject, so the only part missing is hooks before examples. For `before` it's clear; but should we force `after` to be also in the beginning, or maybe option for it's position to be after the examples would be preferable?

**Comment by dgollahon** [comment]
> should we force after to be also in the beginning, or maybe option for it's position to be after the examples would be preferable?

I think the argument for placing `after` before examples is pretty good, especially since you generally will have multiple examples. That said, I'm sure some people will prefer `after` will be after the examples, but we could start without configuration and let people request the feature if they actually want it or just make before the examples the default.
