### ISSUE TITLE
How to configure linting in code editors?

### ISSUE THREAD

**Issue by choosen** [rubocop-hq/rubocop-rspec#592]
I tried using atom and Visual Studio Code - rubocop is working, but without rspec rules.

My setup in VSC: 
```
"ruby.lint":{
  "rubocop": {
     "lint": true,
     "rails": true,
     "require": ["rubocop-rspec"] # this also did not help
  }
}
```

**Comment by dgollahon** [comment]
To be honest, I'm not sure. I remember trying to get this to work with vscode when I was trying it out about 6 months ago, but I never got it quite right.

I'd suggest you ask over at [vscode-ruby](https://github.com/rubyide/vscode-ruby) if you can't make headway.

We do have some various quirks about require order, etc. that can be problematic since there isn't (yet) an official rubocop extension api, so that could be related but I don't have any concrete suggestions for you at the moment.

One thing you might want to check is if `"lint": true` disables non-lint cops as well as enabling the lint cops. If so, it might exclude the `rubocop-rspec` linting, but that's just speculation--I'm not sure how it's implemented (though I think `rubocop -l` has this effect).

**Comment by choosen** [comment]
Posted an issue: https://github.com/rubyide/vscode-ruby/issues/352

**Comment by choosen** [comment]
solved with e.g. `vscode-ruby`  0.22.2
