### ISSUE TITLE
How to “Report the versions of `rubocop-rspec`”

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop-rspec#599]
Our [contributing guidelines](https://github.com/rubocop-rspec/rubocop-rspec/blob/master/.github/CONTRIBUTING.md#issue-reporting) tell our users to

> Report the versions of `rubocop-rspec`, as well as the output of `rubocop -V`

But since there is no `rubocop-rspec -V` tool, how *do* people easily find the version of `rubocop-rspec`? Something like
```
bundle show rubocop-rspec | awk -F'/' '{ print $NF }'
```
or
```
bundle exec ruby -e 'require "rubocop-rspec"; puts RuboCop::RSpec::Version::STRING'
```
should work – should we add such a line to the guidelines? Or add a file in our `bin/` folder, for this one purpose?

**Comment by dgollahon** [comment]
This is a really interesting point. I'm not sure what the right thing to do here is, but of your two proposed solutions I slightly prefer the latter since it happens within ruby / is an api we control.

If we ever get a proper plugin api for `rubocop`, maybe `rubocop -V` could list the versions of its plugins.

**Comment by bquorning** [comment]
> If we ever get a proper plugin api for `rubocop`, maybe `rubocop -V` could list the versions of its plugins.

Yeah, that would be the preferred option.

**Comment by pirj** [comment]
```
$ rubocop -V
  - rubocop-performance 1.9.2
  - rubocop-rspec 2.2.0
```

The issue has been resolved in RuboCop.
