### ISSUE TITLE
CreateList with index

### ISSUE THREAD

**Issue by TomBosmans** [rubocop-hq/rubocop-rspec#702]
```yaml
FactoryBot/CreateList:
  EnforcedStyle: create_list
```
```
test 'create list test' do
  3.times { |n| create :user, created_at: n.months.ago }
end
```
```bash
spec/test_spec.rb:4:3: C: FactoryBot/CreateList: Prefer create_list.
  3.times { |n| create :user, created_at: n.months.ago }
  ^^^^^^^
```

Based on the [docs](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/CreateList) this should not be failing:
```
# bad
3.times { create :user }

# good
create_list :user, 3

# good
3.times { |n| create :user, created_at: n.months.ago }
```

Versions: 
  - rubocop (0.59.2)
  - rubocop-rspec (1.29.1)

**Comment by bquorning** [comment]
@Darhazer Can you have a look? It seems the docs and the specs contradict each other.

**Comment by Darhazer** [comment]
Originally the cop wasn't flagging `times` block when an argument is used. But it turned out that `create_list` also yields a block that can be used to set properties of different instances differently.

Still, when you want to use the iteration number, it's not as convenient, so I'm not sure whether we have to fix documentation or the cop. I would like to ask @composerinteralia for his opinion. 

cc: @pirj

**Comment by composerinteralia** [comment]
`3.times { |n| create :user, created_at: n.months.ago }` seems like it should be allowed, since there is not a great way to do quite the same thing with `create_list`. I think I agree with the documentation on this one.

**Comment by Darhazer** [comment]
I'll update the cop over the weekend
