### ISSUE TITLE
Cop suggestion: Detect missing require of `spec_helper` or `rails_helper`

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-rspec#748]
Sometimes a developer may neglect to add a call to require `spec_helper` or `rails_helper`.

The test may then pass when running as part of the whole suite, but fail when running in isolation.

I think it would be useful to have a cop which checks for a call to require `spec_helper` or `rails_helper` in each spec file (e.g. `spec/**/*_spec.rb`).

For a non-Rails project, it's often sufficient to have a `.rspec` config file which automatically requires `spec_helper`. But for a Rails project, I think it's better to specify the helper in each spec file (e.g. `rails_helper` or `spec_helper`).

**Comment by dgollahon** [comment]
> But for a Rails project, I think it's better to specify the helper in each spec file (e.g. rails_helper or spec_helper).

What would be a reason you wanted to do that? If you force it in every file how is it different than configuring it "globally" in something like `.rspec` or a similar option. I don't understand what the significance of Rails/non-Rails project would be here. Personally, I always define a `.rspec` file.

**Comment by andyw8** [comment]
Since rspec-rails v3, two different helpers for are provided when you install it.

If you're testing a class which doesn't depend on Rails, you can use `spec_helper`. This allows for a very fast startup time.

If you're testing something which does depends on Rails, you use `rails_helper`.

More details: https://relishapp.com/rspec/rspec-rails/docs/upgrade

**Comment by dgollahon** [comment]
Ok, I think I see what you mean now. So you're suggesting a cop that checks that every file has one or the other of those but doesn't care which one?

I guess that could be helpful if you prefer that practice though you wouldn't be able to validate which helper you should have included without running the spec. Most Rails specs I've encountered need rails_helper / both but I just consolidate mine into spec_helper and use `.rspec`.

**Comment by andyw8** [comment]
> Ok, I think I see what you mean now. So you're suggesting a cop that checks that every file has one or the other of those but doesn't care which one?

Yes, that's correct.

I realise that this approach is probably not mainstream, and most people will use `rails_helper` regardless. But I find it useful as it helps me write application logic which is not tightly coupled to Rails framework logic.

This talk by Robert Martin expands on this topic:
Ruby Midwest 2011 - Keynote: Architecture the Lost Years by Robert Martin
https://www.youtube.com/watch?v=WpkDN78P884

**Comment by dgollahon** [comment]
I tried doing specific requires per spec in a project for similar reasons but found that it was extremely difficult to keep in sync/working because most devs would just run the whole test suite which means that the correct/minimal require was not asserted because the missing dependencies were pulled in through other tests so I gave up on it.

If others are interested in this style of requires I don't have a strong opinion on it other than i think it should be disabled by default.

**Comment by andyw8** [comment]
How about enabling by default, but with a constraint: If the project contains an `.rspec` config file, with a line matching `require.*helper`, then the cop is skipped.

**Comment by dgollahon** [comment]
I would still suggest that by default we do nothing or advocate for a `.rspec` file before pushing for replicating a require across a bunch of files by default.

We could also have a cop that just checks for a `.rspec` or make that a style of a spec helper cop that's enabled by default.

**Comment by pirj** [comment]
What do you think about this setup?

```
# .rspec
--require spec_helper
```

```ruby
# spec_helper.rb

RSpec.configure do |config|
  config.define_derived_metadata(file_path: %r{/spec/models/}) { |metadata| metadata[:rails] = true }
  config.when_first_matching_example_defined(:rails) do
    require 'rails_helper'
  end
end
```

[`when_first_matching_example_defined` doc](https://relishapp.com/rspec/rspec-core/docs/hooks/when-first-matching-example-defined-hook).

That's all what's needed in order to run `rspec` with arbitrary specs, and save both some time and one line on `require`.

Works with different types of specs (rubocop, project-local rspec matchers), and Rails engines.

Also, I've seen a severe problem when a spec tried to manually require spec helper file.

**Comment by andyw8** [comment]
@pirj Interesting idea... I'll try this on a small project and see how it feels.

**Comment by pirj** [comment]
Do you think it makes sense to keep this issue open?

**Comment by andyw8** [comment]
Let's close for now.
