### ISSUE TITLE
RSpec/ExampleWording autocorrect breaking code on multiline example strings

### ISSUE THREAD

**Issue by Drowze** [rubocop-hq/rubocop-rspec#792]
When I run `rubocop --require rubocop-rspec --only RSpec/ExampleWording --auto-correct` against the code below:

```
RSpec.describe 'Testing' do
  it 'should be flagged '\
     'but correctly fixed' do
  end
end
```

I get:
```
RSpec.describe 'Testing' do
  it 'is flagged '\ 'but correctly fixed' do
  end
end
```

Which is invalid syntax:
```
bundle exec rspec test_spec.rb                                                                                                                                    13:30:12

An error occurred while loading ./test_spec.rb.
Failure/Error: __send__(method, file)

SyntaxError:
  /Users/rgibim/workspace/ruby-scripts/test-rubocop-rspec/test_spec.rb:2: syntax error, unexpected $undefined, expecting keyword_end
    it 'is flagged '\ 'but correctly fixed' do
                    ^
  /Users/rgibim/workspace/ruby-scripts/test-rubocop-rspec/test_spec.rb:2: syntax error, unexpected keyword_do_block, expecting end-of-input
  ...ged '\ 'but correctly fixed' do
  ...                             ^~
```

**Comment by pirj** [comment]
Quite an interesting case, thanks for reporting.

**Comment by pirj** [comment]
I took a stab at it, a multi-line string literal is parsed as `dstr`. It's not a big deal to combine it.

Joined `node_parts` by `value` to get the original string.
Had to add a check that all `node_parts` are of a `str_type?` though, otherwise, other string interpolation literals cease to work.

Not happy about the code, the things are getting complicated, trying to untangle the code, and will send a pull request.
