### ISSUE TITLE
Misleading naming of `RSpec/ImplicitSubject` cop

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-rspec#808]
[Implicit subject](https://relishapp.com/rspec/rspec-core/v/3-8/docs/subject/implicitly-defined-subject) is a subject inferred from the class being described, e.g.:
```
describe Klass do
  # `subject` is implicitly defined as `Klass.new`
end
RSpec.describe Mod do
  # `subject` is implicitly defined as `Mod` unless `Class === Mod`
end
```

The usages `is_expected` and `should` are called [one-liner syntax](https://relishapp.com/rspec/rspec-core/v/3-8/docs/subject/one-liner-syntax), and don't imply the use of implicit subject, e.g.:
```
RSpec.describe Klass do
  subject(:instance) { Klass.new(1, 2) }

  it { is_expected.to be_a Klass }
end
```

The cop would raise an offence, even though there's an explicitly defined `subject` in this spec.

Additionally, auto-correction to `expect(subject)` is sub-optimal and would trigger `RSpec/NamedSubject`.

What would you say about renaming it to `RSpec/OneLinerSyntax`?

**Comment by dgollahon** [comment]
I don't think `RSpec/OneLinerSyntax` is a good name because the tools used here are not strictly limited to one-line uses, despite the naming in the associated docs. I could write multiple `is_expected`s or spread out one of those onto multiple lines. I think this naming would be at least as confusing.

The original name is talking about _referencing_ the subject implicitly (which is what you are doing when you don't refer to the subject by its name), not _defining_ the subject implicitly. I see where there could be some confusion but I'm not sure it's that significant. Maybe `RSpec/ImplicitSubjectReference` or something?

> Additionally, auto-correction to expect(subject) is sub-optimal and would trigger RSpec/NamedSubject.

Whether it's sub-optimal depends on your testing style I think. I prefer this form to `is_expected` or `should` in my tests but I don't know if that's very common.

For `RSpec/NamedSubject` I don't think that's true--don't we just check on `subject` definitions, not references?

**Comment by pirj** [comment]
Fair enough on referencing the subject implicitly.

`NamedSubject`, however, has this spec:
```ruby
          it "is valid" do
            expect(subject.valid?).to be(true)
                   ^^^^^^^ Name your test subject if you need to reference it explicitly.
```

Considering that the renaming itself will encumber the users to rename the cop in their config files it's just not worth it at this point.

**Comment by dgollahon** [comment]
> `NamedSubject`, however, has this spec.

huh! I forgot it worked like that. I guess that makes sense for the case where the subject is defined implicitly but it doesn't make sense if it's included from elsewhere. I guess that's why we have the `IgnoreSharedExamples` option. 

> Considering that the renaming itself will encumber the users to rename the cop in their config files it's just not worth it at this point.

Agreed. Maybe worth considering on a major version change or something if we have a lot of renames we want to do?
