### ISSUE TITLE
Suggestion: Disable `RSpec/DescribeClass` for versions

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop-hq/rubocop-rspec#889]
Hello!

I have (almost standard from `bundle gem`) gem version spec:

```ruby
# frozen_string_literal: true

describe 'FooBar::VERSION' do
  subject { FooBar::VERSION }

  it { is_expected.to match(/\d+\.\d+\.\d+/) }
end
```

And it causes an offense:

```
RSpec/DescribeClass: The first argument to describe should be the class or module being tested.	
```

Also, my DRY version:

```ruby
describe(const_name = 'FooBar::VERSION') do
  subject { Object.const_get(const_name) }
```

---

If I'd have `describe FooBar::VERSION do`, then output of specs (`--format=doc`) will contain `VERSION` value instead of constant name, and `described_class` will be `nil`.

**Comment by pirj** [comment]
Agree that this cop should be relaxed so that a string literal is accepted as well.
This is a common practice to avoid autoloading all the described constants before they are needed and to prevent load order issues.

The only thing I would double-check that Describe**d**Class (another cop) with `EnforcedStyle: described_class` behaves correctly, especially in scenarios with interleaved nested class/string arguments (example of nested https://github.com/rubocop-hq/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/described_class_spec.rb#L234).

Nice catch regarding "then output of specs will contain VERSION value instead of constant name" :+1:, https://github.com/rubocop-hq/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/described_class_spec.rb#L274 needs to be fixed.

Would you like to tackle this @AlexWayfer ?

**Comment by AlexWayfer** [comment]
> Would you like to tackle this @AlexWayfer ?

Sorry, but I'm not familiar with RuboCop (nodes), so I can't promise. But maybe sometime if nobody will care about it and I will be bored… :grimacing:

**Comment by pirj** [comment]
We'll provide all necessary guidance, and actually no node pattern knowledge is required to do this, I imagine you'll have to take a docstring, call something like `str_type?`/`sym_type?` on it, and make sure it looks like a constant (capitalized, has double colons etc), or find a better way to evaluate that.

There's doubtfully anyone picking this up before you, you can see the backlog, and it's more like scratching your own itch (for everyone else to benefit). And, believe me, you can do it! We have [15 first-time contributors](https://github.com/rubocop-hq/rubocop-rspec/blame/master/CHANGELOG.md#L482) since last year.

**Comment by AlexWayfer** [comment]
@pirj thank you for your support! I've created #891.
