### ISSUE TITLE
RSpec/VariableName has the wrong namespace - should be Naming

### ISSUE THREAD

**Issue by modosc** [rubocop-hq/rubocop-rspec#931]
with the upgrade to 1.40.0 we wanted to disable `RSpec/VariableName`. i added this to our `.rubocop.yml`:

```yaml
RSpec/VariableName:
  Enabled: false
```

and now when i run rubocop i get this warning:

```
.rubocop.yml: RSpec/VariableName has the wrong namespace - should be Naming
```

and errors still come up:
```
spec/graphql/mutations/update_job_status/accepted_spec.rb:307:19: C: RSpec/VariableName: Use snake_case for variable names. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/VariableName)
              let(:statusReason) { custom_status_reason_type.text }
```

how can we disable this rule? we're using `rubocop-0.83.0`

**Comment by pirj** [comment]
Can you please check if it's the same problem as https://github.com/rubocop-hq/rubocop/issues/8044? Wondering what happens if you disable `RSpec/FilePath` cop.

Can you provide a minimal reproduction example (as a git repo)? I've locked `rubocop` to 0.83.0 and tried to reproduce on this repo, but there's no warning.

What happens if you disable the cop by putting this part of config into `spec/.rubocop.yml`?

**Comment by madlew** [comment]
The same issue on my end:
Rubocop 0.87.1
```.rubocop_todo.yml: RSpec/VariableName has the wrong namespace - should be Naming```

It seems it's not possible to disable RSpec/VariableName since it somehow interacts with rubocop's Naming/VariableName

As a result, my todo list with both RSpec/VariableName and Naming/VariableName defined with a list of exclusions does not work. If I remove RSpec/VariableName from rubocop_todo list, exclusions for Naming/VariableName work as expected.
